# Generated by Django 5.0.2 on 2024-11-13 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Whispr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='reunion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='reunion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='Whispr.empresa'),
        ),
        migrations.CreateModel(
            name='Transcripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada')], default='EN_PROCESO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripciones', to='Whispr.reunion')),
            ],
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.TextField()),
                ('puntos_clave', models.TextField()),
                ('sugerencias', models.TextField()),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('transcripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='Whispr.transcripcion')),
            ],
        ),
    ]
